[package]
name = "magdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
hex = "0.4.3"
popol = "3.0.0"
rand = "0.8.5"
url = "2.4.0"
urlencoding = "2.1.2"
