[package]
name = "magdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
url = "2.4.0"
urlencoding = "2.1.2"
